[build]
command = """
    wget -qO- https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.4-stable.tar.xz | tar xJ
    export PATH="$PWD/flutter/bin:$PATH"
    flutter build web --release
  """
publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200